spring:
  application:
    name: fridge-server
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    url: jdbc:mysql://nfcv.xyz:3306/fridge?useUnicode=true&characterEncoding=utf8
    username: dbuser
    password: dbpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 120000
      connection-test-query: SELECT 1
  redis:
    host: redis.huhaorui.com
    password: 0660f9bbf315
    port: 6379
server:
  port: 8082

robot:
  ruyi:
    app_key: fad0708d-0c8f-456c-a022-0660f9bbf315

  tuling:
    key: 47f4c028a5fd12419c90f18da6524169
